#+Title Simple_to_complex_contagion_in_collective_decision-making

We have made extensive use of the graph-tool package https://graph-tool.skewed.de/ to generate and analyze networks quickly. Some networks are provided in the graph-tool binary file format, and can only be read. Likewise running the network generating python scripts will require this package. We include our data in .csv files, that should be readily accessible. If need be for access to the specific networks, please contact me here or through the email that is given in the paper.

* LTM
Figure 1 of the paper can be generated by evaluating the script with a python terminal, or by running
#+begin_src python
python3 Figure1.py
#+end_src

Which will generate Figure 1 from both the main paper and the supplementary material

[[file:figures/fig1/fig1_0.3.pdf][Figure 1 from the paper]]

The data is included in [[file:network_props.csv][network_props.csv]] and [[file:polarization.csv][polarization.csv]]. The full network data takes up a large amount of space, but a sample is provided in the networks folder, and it is possible to generate more networks using the [[file:LTM_main.py][LTM_main.py]] script.

The networks are saved as graph-tool binary files. Upon special request other formats can be provided.

* Leader Follower Consensus
Figure 2 of the paper can be generated by evaluating the python script with a python terminal, or by running

#+begin_src python
python3 Figure2.py
#+end_src
The data is included under the networks folder as networks/240/{degree}/*.csv. There is a csv for the gains, and one for the network propreties, with the same indices for the networks e.g, [[file:networks/240/16/smallworld_corr_gains.csv][smallworld_corr_gains.csv]] and [[file:networks/240/16/smallworld_props.csv][smallworld_props.csv]].

The network files take up too much space for them all to be included, but there is a sample of the modified Holme-Kim models in networks/240/4/mhk, and one of the small world networks in networks/240/smallworld. The networks are in the graph-tools binary format, saved along with their respective collective frequency responses.

The network properties are calculated with the same functions from the network_functions script. The gain is calculated using the [[file:gain_analyser.py][gain_analyser.py]]  which can also be used to increase the frequency resolution if need be. The [[file:corr_network_data_manager.py][corr_network_data_manager.py]] extract the info from the network .gt files and saves it in .csv files under the respective network degrees. They are then combined and the correlations are calculated in [[file:Figure2.py][Figure2.py]] where the figures display the result.
