#+Title Simple_to_complex_contagion_in_collective_decision-making

We have made extensive use of the graph-tool package https://graph-tool.skewed.de/ to generate and analyze networks quickly. Some networks are provided in the graph-tool binary file format, and can only be read. Likewise running the network generating python scripts will require this package. We include our data in .csv files, that should be readily accessible. If need be for access to the specific networks, please contact me here or through the email that is given in the paper.

* LTM
Figure 1 of the paper can be generated by evaluating the script with a python terminal, or by running
#+begin_src python
python3 Figure1.py
#+end_src

Which will generate Figure 1 from both the main paper and the supplementary materile

[[file:figures/fig1/fig1_0.3.pdf][Figure 1 from the paper]]

The data is included in network_props.csv and polarization.csv. The full network data takes up a large amount of space, but a sample is provided in the networks folder, and it is possible to generate more networks using the LTM_main.py script.

The networks are saved as graph-tool binary files. Upon special request other formats can be provided.
